### ISSUE TITLE
cron reached maximum iterations

### ISSUE THREAD

**Issue by bradleyy1012** [kelektiv/node-cron#409]
I received this error out of nowhere. If I change it from '0 0 6-9 * * *' to '0 0 * * * *' it works again.

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 6,7,8,9 * * * - UTC offset: -07:00 - current Date: Sat Mar 09 2019 18:05:37 GMT-0700

**Comment by bradleyy1012** [comment]
It just happened again after i fixed it. 

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0 10,11,12,13,14,15,16,17,18,19,20,21 * * * - UTC offset: -05:00 - current Date: Sat Mar 09 2019 19:21:27 GMT-0700

**Comment by shuat** [comment]
@bradleyy1012 See this issue https://github.com/kelektiv/node-cron/issues/408#issuecomment-471242670

**Comment by bradleyy1012** [comment]
thanks! issue was resolved by upgrading to 1.6.0

**Comment by mikelam14** [comment]
It is not solved. I am using version 1.8.2 and still get the same error.

**Comment by DavyCode** [comment]
> It is not solved. I am using version 1.8.2 and still get the same error.

Have you resolved this issue?

Error: Something went wrong. cron reached maximum iterations.
Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
Time Zone: "" - Cron String: 0 0,4,8,12,16,20,24,28,32,36,40,44,48,52,56 * * * * - UTC offset: +01:00 - current Date: Thu Oct 29 2020 07:16:09 GMT+0100


Ran into it twice already, it just started all of a sudden

**Comment by sandorvasas** [comment]
1.8.2 and just got this
