### ISSUE TITLE
 Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by shivam-postman** [kelektiv/node-cron#467]
We got the following error message:
`Error: Something went wrong. cron reached maximum iterations.`

Along with it, there was this string:
`Time Zone: "" - Cron String: 0,15,30,45 * * * * * - UTC offset: +00:00 - current Date: Wed Feb 12 2020 04:07:14 GMT+0000`

It'd be great if you guys can let me know some whereabouts of it; would be helpful in finding the side effects of the said error. Thanks.

**Comment by mryellow** [comment]
https://github.com/kelektiv/node-cron/issues/408

**Comment by pddivine** [comment]
I ran into the same issue as well:

`Error: Something went wrong. cron reached maximum iterations.
                                                Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
                                                Time Zone: "" - Cron String: 0,15,30,45 * * * * * - UTC offset: +00:00 - current Date: Mon May 04 2020 01:05:26 GMT+0000`

**Comment by ncb000gt** [comment]
I pushed up a PR with some changes to allow a "soft warning". Can you please test and report back?

**Comment by kasir-barati** [comment]
@pddivine @shivam-postman  Can you give me a script which reproduce/potentially reproduce the same issue?

**Comment by intcreator** [comment]
has this been an problem since the move from Moment to Luxon? if not we can close this issue

**Comment by mryellow** [comment]
This can't really be fixed without a major refactor.

**Comment by intcreator** [comment]
@mryellow what exactly about that function needs to be changed?

**Comment by ledlamp** [comment]
i suddenly started getting this error 100% of the time, as of about 2023-03-05T08:00:05.020Z 🤨

**Comment by ledlamp** [comment]
It looks like this has been fixed by https://github.com/kelektiv/node-cron/pull/639

**Comment by arhip144** [comment]
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-16T12:08:05.798+05:00
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-16T08:17:05.816+05:00
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-16T06:29:06.054+05:00
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-16T04:53:06.068+05:00

**Comment by arhip144** [comment]
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-17T06:01:05.455+05:00
                            Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-17T09:56:05.853+05:00
                             Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-18T05:35:05.982+05:00
                            Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-19T07:12:05.190+05:00
                            Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-19T08:55:05.207+05:00

**Comment by intcreator** [comment]
@arhip144 could you give some more context as to what was going on in the environment when this issue occurred? was the CPU usage high for example?

could you also include which version of node-cron you're using?

**Comment by intcreator** [comment]
ok I would at least try upgrading to 2.3.0 and see if that fixes your issue @arhip144

**Comment by arhip144** [comment]
> ok I would at least try upgrading to 2.3.0 and see if that fixes your issue @arhip144
Updated to 2.3.0
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-22T11:38:05.708+05:00
                            Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-22T08:22:06.174+05:00
                            Time Zone: "" - Cron String: 0 * * * * * - UTC offset: -60
                            - current Date: 2023-03-22T07:36:05.932+05:00

**Comment by toume** [comment]
We just add this issue overnight with code both in prod and that could be reproduced in local. 
The same code was running fine previously. 
Commenting one the call solved the issue.

(note:  we are using "@nestjs/schedule": "^2.2.0" which is using "cron": "2.2.0")

**Comment by intcreator** [comment]
@toume what exactly was it that you commented that solved the issue? we just added some time change fixes in 2.3.0 so if nestjs can update maybe that will fix some issues. otherwise if you can duplicate it with a test that would be much appreciated!

**Comment by peganovme** [comment]
Still have this problem, from time to time. Do I need to provide more info?
![Screenshot 2023-03-30 at 13 10 14](https://user-images.githubusercontent.com/51890259/228804528-608a8ade-751c-49b0-844e-0dbaeccf0533.png)

**Comment by intcreator** [comment]
@peganovme sure:
1. can you tell if cron is running in an environment that's short on CPU/RAM/other resources?
2. did this occur during a daylight savings change or while a change was made to system time?
3. are there system intensive operations running in your `onTick` function?

**Comment by peganovme** [comment]
@intcreator
1. Maybe 
2. No, had before
3. Seems to be not

**Comment by intcreator** [comment]
@peganovme would you mind doing some more testing in your system with the RAM issue? if this error can be reproduced by severely limiting the RAM and mitigated by providing enough RAM resources, that might be the solution to this issue. we could try to detect when we get out of sync but that sounds like a massive problem to solve

**Comment by Weeeendi** [comment]
error: uncaughtException: Something went wrong. It took over five seconds to find the next execution time for the cron job.
Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0
                                                        - current Date: 2023-04-10T04:05:20.352+00:00

**Comment by Weeeendi** [comment]
> error: uncaughtException: Something went wrong. It took over five seconds to find the next execution time for the cron job. Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0 - current Date: 2023-04-10T04:05:20.352+00:00

It works now, because I ran it by root.

**Comment by Daedalline** [comment]
Also seeing this.

Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
                                                        Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
                                                        Time Zone: "" - Cron String: 0 15 * * * * - UTC offset: 0
                                                        - current Date: 2023-04-13T00:18:19.605+00:00

**Comment by gramakri** [comment]
Just hit this one in our code:

```
Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
							Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0
							- current Date: 2023-04-25T07:23:15.830+00:00
    at CT._getNextDateFrom (/home/yellowtent/box/node_modules/cron/lib/time.js:272:12)
    at CT.sendAt (/home/yellowtent/box/node_modules/cron/lib/time.js:185:17)
    at CT.getTimeout (/home/yellowtent/box/node_modules/cron/lib/time.js:202:29)
    at CJ.start (/home/yellowtent/box/node_modules/cron/lib/job.js:118:31)
    at Timeout.callbackWrapper [as _onTimeout] (/home/yellowtent/box/node_modules/cron/lib/job.js:171:11)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by mryellow** [comment]
Just stopping by to say I find this the most entertaining issue on the internet.

I can watch a video where a replica Antikythera mechanism predicts solar ellipses or where the next Olympics should be held at the turn of a dial, then switch over and read the daily notifications about attempting to figure out the next scheduled date in a cron library.

**Comment by phongvuhyuet** [comment]
```
Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: "" - Cron String: 0 0 10 * * * - UTC offset: 540
							- current Date: 2023-05-21T19:34:40.083+09:00
```

**Comment by intcreator** [comment]
this issue likely has a variety of causes. it's kind of like creating an issue for the blue screen of death on windows. I think the solution to this issue is to add some more debugging information that can be output when the failsafe is triggered and see if it's due to the environment in which node cron is run in for example

**Comment by mryellow** [comment]
>  when the failsafe is triggered

First there needs to be a failsafe.

Something like:

```
while (cnt < somelimit) {
  cnt++
```

**Comment by intcreator** [comment]
that's what "maximum iterations" is; basically if the time that node cron is keeping track of is more than five seconds off from what the time actually is, we bail. so the idea is adding more debugging info when we bail

**Comment by oh2th** [comment]
Interesting, I'm getting error every now and then, but what I now noticed:
```
Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
							Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0
							- current Date: 2023-05-30T09:46:09.509+00:00
```
Is that the error event actually happened on 2023-06-02 at approx 21:53 UTC. This the time that the system sent an email to me about the crash.

**Comment by sheerlox** [comment]
I tried running tests with very limited resources (to simulate the server being under high load), and as expected this error was thrown multiple times (on 11 tests out of 125 total).

Command used to run the tests: `systemd-run --scope -p MemoryMax=64M -p MemoryHigh=52M -p CPUQuota=1% npm run test`

<details>
  <summary>List of all the tests that failed</summary>
  
  - `crontime › should generate the right next days when cron is set to every 15 min`
  - `crontime › should work around time zone changes that shifts time back (1)`
  - `crontime › should work around time zone changes that shifts time forward`
  - `crontime › Should schedule jobs inside time zone changes that shifts time forward to the end of the shift, for weekly jobs`
  - `crontime › Should schedule jobs inside time zone changes that shifts the time forward to the end of the shift, for daily jobs`
  - `crontime › Should schedule jobs inside time zone changes that shifts the time forward to the end of the shift, for hourly jobs`
  - `crontime › should generate the right N next days for * * * * *`
  - `crontime › should generate the right  N next days for 0 0 9 * * *`
  - `crontime › should generate the right  N next days for 0 0 * * * with a time zone`
  - `crontime › should generate the right  N next days for */3 * * * * with a time zone`
  - `crontime › should test valid range of months (*/15 * * 6-11 *)`
</details>  

---

![image](https://github.com/kelektiv/node-cron/assets/11234273/7c6f71f9-9cb7-40cb-a299-16896145a458)

---

![image](https://github.com/kelektiv/node-cron/assets/11234273/6af0c7b5-2650-4646-b2b1-760cbf408f47)

**Comment by intcreator** [comment]
nice! I wonder if there's a way to detect high system load a little better than just our own app taking a long time and then notify the user of that issue. previously a soft failure was considered which I feel is better than our app forcing a crash. that leaves room for recovery and hopefully successful execution of future jobs. as long as we notify the user that there was a failure and as long as we can "catch up" once there are more resources I would prefer that

**Comment by sheerlox** [comment]
@intcreator are you referring to #499? While I definitely agree with you, at the same time the [comment made by Nick about this](https://github.com/kelektiv/node-cron/pull/499#issuecomment-679414839) also makes sense to me.
The only way I see (for now and with my limited knowledge of the codebase) to tackle this issue is to understand the conditions under which an infinite loop would exist and write safeguards specific to that. What do you think?

**Comment by intcreator** [comment]
yeah that's the issue I was referring to.

maybe instead of crashing we can restart the cron job with a warning? that way the infinite loop is prevented but the cron job can still be running afterward

**Comment by cexedev** [comment]
Has anyone found the fix yet,
`
let resetNotificationFlagIfFailed = new CronJob(
  `*/20 * * * * *`,
  async function () {
    ... MY CODE HERE
  },
  null,
  true,
  "Australia/Brisbane"
);`

This is how I've running a cronjob and this is the error i am getting
`
Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
							Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
							Time Zone: "" - Cron String: 0,15,30,45 * * * * * - UTC offset: 600
`

**Comment by mryellow** [comment]
This package works in the cases where `node-cron` does not.

https://github.com/harrisiirak/cron-parser

I'd suggest moving to it entirely or replacing `_getNextDateFrom` with this library.

**Comment by jakguru** [comment]
Got this error: `Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.`
Here's the string that it asked for:

Time Zone: "" - Cron String: 0 * * * * * - UTC offset: 0 - current Date: 2023-07-13T22:18:41.049+00:00
Node.js v18.16.1

**Comment by sheerlox** [comment]
Hey there! As stated above, we released a fix for this issue in `v2.4.1` 🎉 

We expect this change to fix the majority of cases you encountered, which we believe were mostly related to low resources environments.

Please update to that version, and open a new issue if you encounter a similar issue again (if no one opened one already).

**Comment by olegktrnd** [comment]
I'm still encountering this issue. Here's what the full error looks like:

```
Error: Something went wrong. It took over five seconds to find the next execution time for the cron job.
                            Please refer to the canonical issue (https://github.com/kelektiv/node-cron/issues/467) and provide the following string if you would like to help debug:
                            Time Zone: "" - Cron String: 0,10,20,30,40,50 * * * * * - UTC offset: 0
                            - current Date: 2024-04-30T00:25:28.650+00:00
   at CT._getNextDateFrom (/opt/app/node_modules/cron/lib/time.js:272:12)
   at CT.sendAt (/opt/app/node_modules/cron/lib/time.js:185:17)
   at CT.getTimeout (/opt/app/node_modules/cron/lib/time.js:202:29)
   at CJ.start (/opt/app/node_modules/cron/lib/job.js:119:31)
   at Timeout.callbackWrapper [as _onTimeout] (/opt/app/node_modules/cron/lib/job.js:172:11)
   at listOnTimeout (node:internal/timers:564:17)
   at processTimers (node:internal/timers:507:7)>
```
   
   My node-cron version is v3.0.3. 
   I get this error about 2-3 times a day. Any ideas what could be causing it?

**Comment by sheerlox** [comment]
Hi, this bug [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) **in v2.4.1, so upgrading to (at least) that version will resolve your issue**.

**Comment by dipakpandey7** [comment]
<img width="1604" alt="Screenshot 2024-09-20 at 9 22 38 AM (1)" src="https://github.com/user-attachments/assets/13a698e0-3f4c-4478-8cb3-30071eefcb55">


My node-cron version is "cron": "^2.1.0",
I get this error about 2-3 times a day. Any ideas what could be causing in and how to solve this issue

**Comment by sheerlox** [comment]
@dipakpandey7 your version is probably pinned in your package manager lock file, so the same recommendation as above apply

**Comment by intcreator** [comment]
this issue has been fixed as of v2.4.1. if you have updated to v2.4.1 or later and are still having problems, please open a new issue.
