### ISSUE TITLE
Builder for Cron job strings

### ISSUE THREAD

**Issue by mahyarmirrashed** [kelektiv/node-cron#582]
If we could have something to discordjs/builders for slash commands, that would be great!

It would make creating the cron jobs less cryptic (e.g. '0 0 * * MON').

**Comment by intcreator** [comment]
that's out of the scope of this project. even Discord.js has them as a separate package. feel free to start working on a package yourself that builds cron strings though. if it looks good we might reference it in the README

cron syntax is a little tricky to understand at first but part of the appeal is that it's very concise

**Comment by mahyarmirrashed** [comment]
Here is a package that I developed for this role: [`cron-compose`](https://github.com/mahyarmirrashed/cron-compose).

There's some future ideas in the `ROADMAP.md`, feel free to open issues to create more feature requests or to file bugs. I hope that it is good to reference in your project's `README`. I spent a lot of time thinking about how I wanted to design it and I finally came up with this declarative builder format.

I find it to be more straightforward than the alternative of something like `node-cron-expression`.

Let me know your thoughts! Excited to hear what you think of this.

**Comment by sheerlox** [comment]
Hey @mahyarmirrashed :wave: Thanks for sharing your work with us! I've added the right labels so this issue can be [found more easily](https://github.com/search?q=repo%3Akelektiv%2Fnode-cron++label%3Atype%3Afeature+builder&type=issues) by potential future users of your library :wink: 

In my opinion (as a seasoned UNIX / Node cron user), `1 * 1-14 * *` is way more readable than
```js
const cronExpr = new CronComposer()
  .addSingle(SlotType.Minute, 1)
  .addRange(SlotType.Day, 1, 8)
  .addRange(SlotType.Day, 6, 14)
  .toString();
```

Something that would look more attractive to me (although I probably wouldn't use it either :joy:) would be chainable human-readable functions, like `composer.every("2 days").at("10 pm").except.on("tuesdays and sundays")`! you could imagine the same 

That being said, your library will probably be very useful to a lot of developers who need to build cron expressions dynamically, so congrats on developing that library!

Here are a few thoughts:
- README documentation
  - should mention the returned cron expression in the usage example for clarity
  - does not make explicit what the default (`*`) for an unspecified field is
- testing is still at an early stage, with test coverage (branch) only at `57%`, getting good unit testing for all functions should be a priority
- ROADMAP
  - regarding the human-readable string generation, that could be out of scope for your library, and there's already the [`cronstrue`](https://github.com/bradymholt/cronstrue) library which is maintained (and sizes an impressive 1.3MB, probably because of the "i18n support with 30+ languages")
  - love the "intersection and union between `CronComposer` instances" feature, and if you could think about adding a `from()` method to create a `CronComposer` instance from a cron expression, that feature could be really useful for more people!

I would have enjoyed contributing to your library, unfortunately, I'm already grappling to find some time for a lot of things that are on my mind.

_Note: I tried running the example from the README, and it returned `1 * 1-13 * *`, I'm not sure but I guess that's a bug since I would expect `1-14`. let me know I'll be glad to open the first bug report :wink: (P.S. issues don't seem to be enabled on the repository)_

**Comment by mahyarmirrashed** [comment]
Hi @sheerlox , thank you so much for your in-depth review, comments, and expertise! (Not to mention so fast!) That kind of review and thoughts were exactly what was I hoping for 😄 

Thanks for mentioning that issues were turned off. I am not sure how I would have been alerted otherwise, lol!

I looked into the bug that you mentioned between `1-13` and `1-14`. That was because in my first draft (yesterday), I had the upper bound for the range set as exclusive. I realized by adding more tests that it would not be valid because how would you specify that you wanted to include something like `dec`. So, I made a breaking change to set the upper bound of the range as inclusive. It should now behave as expected. I've added to the `ROADMAP.md` to have some documentation on the methods so that people won't have to guess when using the methods.

Thanks for sharing `cronstrue`, that would actually pair really nice with my library and provides all the human-readable string generation and you mentioned (so no need to duplicate the work!).

I think that the chain-able human readable functions would be an excellent idea. I've added it to the `ROADMAP.md` and I'll be thinking about how to implement that effectively. I've also added the idea of adding a `from()` method for the `CronComposer` as you mentioned. That would definitely be useful indeed.

I've edited the example in the `README.md` so that it shows the expected value. I'll be adding mention that the default for the slot is indeed the `*` value.

I added a bunch more tests and now I have 100% coverage on everything. Great suggestion. I found a few more bugs that I had not accounted for.

Regarding the intersection and union idea, I'd love to discuss it some more with you since I'm not 100% clear on what to do there. I think that the intersection one is pretty straightforward. It would just throw an error if there is no valid intersection between the two cron expressions. For example, every Wednesday and every Friday would have no intersection (as far as I can tell). In regards to the union, I don't think that would be possible for some cases either. Not really sure how to determine that, but I can think of some cases where it would not be defined. I think the idea of the intersection/union is much more well-defined for the individual slots than the entire cron expression. Again, love to hear your thoughts on it as a seasoned developer and how often you've found that you might have wanted something like that. (I'm also struggling to find a use case for it 😆 !)

Cheers and thanks for the kind words, review, and star :)

**Comment by mahyarmirrashed** [comment]
Hi again @sheerlox , I've implemented the intersection and human-readable composition API as well now. Let me know your thoughts on it and how you think that I could get the word out more about my package.

**Comment by sheerlox** [comment]
Hey @mahyarmirrashed, sorry for the delay, I was AFK for a few days and then had a lot of things to catch back to (and still have a lot to do).

> how often you've found that you might have wanted something like that. (I'm also struggling to find a use case for it 😆 !)

Honestly, I don't have any use case in mind either :sweat_smile: I think it's a good idea, at least from an engineering perspective it's an interesting problem to try to tackle! As I said before I'm not in the target for your library, so I don't see myself using it (I'd much rather use plain old cron strings), but I'm sure you'll find interested users.

> I've implemented the intersection and human-readable composition API as well now

I've checked the README example for the human-readable composition API and it looks great! I would love to give a deeper look at the underlying code but I unfortunately don't have the capacity at the moment. I'm still watching the repo changelog from afar and will try to find some time in the future for a bit of code review :smile: 

> how you think that I could get the word out more about my package.

I think a good way of doing this is searching GitHub issues in cron-related projects (or heavily cron-dependent) for people encountering problems your library could solve, and trying to get in touch with the maintainers (or directly the users if integrating into the project is out of scope) to describe your solution and how to implement it :wink: 

Wishing you all the best in your OSS adventure! :rocket:

**Comment by mahyarmirrashed** [comment]
Thanks @sheerlox for your response and the example of the "marketing"! Super appreciated :) 🚀
